### ISSUE TITLE
JDBC driver prepareStatement method is incorrect

### ISSUE THREAD

**Issue by mainstreet439** [omnisci/omnisci-jdbc#14]
Several methods throw an exception (per below)  except the following

  public PreparedStatement prepareStatement(String sql)
    throws SQLException
  {
    return new MapDPreparedStatement(sql, this.session, this.client);
  }

If an application subsequently calls getMetadata on the returned object it fails. This can cause an application to fail unless it is coded to avoid using the Prepare method 

public ResultSetMetaData getMetaData()
    throws SQLException
  {
    throw new UnsupportedOperationException("Not supported yet, line:" + new Throwable().getStackTrace()[0].getLineNumber() + " class:" + new Throwable().getStackTrace()[0].getClassName() + " method:" + new Throwable().getStackTrace()[0].getMethodName());
  }
  

It looks like MAPD's driver has a hacked solution for prepare which needs sorting out.

  public PreparedStatement prepareStatement(String sql, String[] columnNames)
    throws SQLException
  {
    throw new UnsupportedOperationException("Not supported yet, line:" + new Throwable().getStackTrace()[0].getLineNumber() + " class:" + new Throwable().getStackTrace()[0].getClassName() + " method:" + new Throwable().getStackTrace()[0].getMethodName());
  }

**Comment by Smyatkin-Maxim** [comment]
`getMetadata()` for prepared statement has been implemented in this "hacky" way here 4b0e097c91e214019f827c8744d61ad2ff1b16a2 by selecting with limit 0 to simulate `DESCRIBE`, which we indeed are unlikely to support in a near future
