### ISSUE TITLE
JDBC/Thrift Java Code should be in Maven

### ISSUE THREAD

**Issue by baank** [omnisci/omnisci-jdbc#15]
It is not acceptable to just force users to embed the map*dependencies.jar files.

For one it prevents us from excluding transitive dependencies, in particular your use of SLF4J which prevents MapD from being used in Play applications.

Instead all your Java code should be stored in a Maven repo. Either a public one or self hosted.

**Comment by randyzwitch** [comment]
Closing, since this issue is now resolved. Will add the directions to the README
