### ISSUE TITLE
how insert array field through jdbc  ?

### ISSUE THREAD

**Issue by ggcking** [omnisci/omnisci-jdbc#20]
I want to batch insert a array field into a table by java code;
how to do this throgh jdbc ?

**Comment by cdessanti** [comment]
Hi @ggcking ,

I did implement the setArray method on jdbc driver. 

You can download the driver following this link [http://www.mediafire.com/file/vh76ipk65s7j48s/jdbc-4.7.0-jar-with-dependencies.jar/file].

If you run into issues, please report, and please don't close this Github issue.

**Comment by ggcking** [comment]
@cdessanti 
hi，i try to the new jdbc driver, it works .thk.

**Comment by cdessanti** [comment]
Could you reopen the issue? I need it open to do a pr.
Thanks in advance

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by ggcking** [comment]
@cdessanti 
If it have a new update, please let me know, thanks.

**Comment by cdessanti** [comment]
It's taking a little longer than expected because I am implementing getArray method.
If you have issues with the setArray and bulk inserts let me know (it works for monodimensional arrays only)

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by Smyatkin-Maxim** [comment]
It has been fixed with 2cff14500ac3e1c2d15dda57780630b0fe0a1b8c , which adds arrays support into the driver
