### ISSUE TITLE
querytimeout

### ISSUE THREAD

**Issue by ggcking** [omnisci/omnisci-jdbc#21]
hi, I have a query that takes a little bit time, the jdbc return timecount error. Have the driver some params of query timeout?

**Comment by cdessanti** [comment]
Nope there isn't anything in jdbc that would return a timeout,  so it has to be a thrift exception.
How much time the query would run?

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by ggcking** [comment]
@cdessanti about 3-5 minitues.

**Comment by Smyatkin-Maxim** [comment]
Closing it as it doesn't seem to be related to the driver. Feel free to reopen if I'm wrong
