### ISSUE TITLE
Maven JAR "skinny" vs OmniSci tarball install "fat" JAR

### ISSUE THREAD

**Issue by randyzwitch** [omnisci/omnisci-jdbc#22]
Per this tweet: https://twitter.com/the1dv/status/1213308761537798146

When trying to use the JDBC driver via JetBrains, downloaded from Maven, you get a slf4j error:
![image](https://user-images.githubusercontent.com/2762787/71824809-62c48600-3068-11ea-9bff-022a1590d86f.png)

If you use the JDBC driver provided within the OSS tarball (https://releases.omnisci.com/os/tar/omnisci-os-latest-Linux-x86_64-cpu.tar.gz), connection succeeds

If this is intentional, we need to find a way to document that the Maven driver intentionally does not include the slf4j driver. If it's not intentional, then we should provide a "fat" JAR replacement on Maven.

**Comment by Smyatkin-Maxim** [comment]
Yes, it's intentional and expected from a maven build - it should not include any dependencies. If dependencies are needed, I've added a maven profile to build a fat jar in a07520d8136b0c6c663515167807047b38c98cd6. There are instructions how to do it in the README.
